alter table public.battle_top_scores
  add column if not exists player_id text;

create index if not exists battle_top_scores_player_id_idx
  on public.battle_top_scores (player_id);

drop view if exists public.battle_top_player_bests;

create view public.battle_top_player_bests
with (security_invoker = true)
as
select client_event_id, nickname, avatar, top_name, score, won, created_at, player_id
from (
  select
    client_event_id,
    nickname,
    avatar,
    top_name,
    score,
    won,
    created_at,
    player_id,
    row_number() over (
      partition by coalesce(player_id, 'legacy:' || lower(btrim(nickname)) || '::' || avatar)
      order by score desc, created_at asc, client_event_id asc
    ) as player_rank
  from public.battle_top_scores
) ranked
where player_rank = 1;

create table if not exists public.battle_top_matches (
  id bigint generated by default as identity primary key,
  client_match_id text not null unique,
  challenger_player_id text not null,
  challenger_nickname text not null,
  challenger_avatar text not null,
  challenger_top_name text not null,
  defender_player_id text not null,
  defender_nickname text not null,
  defender_avatar text not null,
  defender_top_name text not null,
  challenger_won boolean not null,
  score integer not null,
  created_at timestamptz not null default now()
);

create index if not exists battle_top_matches_defender_created_idx
  on public.battle_top_matches (defender_player_id, created_at desc);

alter table public.battle_top_matches enable row level security;
revoke all on public.battle_top_matches from anon, authenticated;
